-- ============================================================
-- BahasaBelajar：多用户登录 + 文章笔记 迁移
-- 睡醒后操作：先做【第 0 步】(Dashboard)，再把【第 1~6 步】整段粘进 SQL Editor 运行。
-- 你选择了「清空重来」，所以会清掉现有的学习进度/打卡（词库/文章/语法/文化都保留）。
-- ============================================================

-- 【第 0 步 · 在 Dashboard 操作，不是 SQL】
--   Authentication → Providers(或 Sign In/Up) → Email → 关闭 "Confirm email"
--   这样注册后能立即登录，无需收确认邮件。（个人 app 推荐关）

-- 【第 1 步】清空旧的单用户进度
truncate table learning;
truncate table checkins;

-- 【第 2 步】给进度表加 user_id（默认=当前登录用户），主键改为含 user_id
alter table learning add column if not exists user_id uuid not null default auth.uid() references auth.users(id) on delete cascade;
alter table learning drop constraint if exists learning_pkey;
alter table learning add primary key (user_id, word_id);

alter table checkins add column if not exists user_id uuid not null default auth.uid() references auth.users(id) on delete cascade;
alter table checkins drop constraint if exists checkins_pkey;
alter table checkins add primary key (user_id, date);

-- 【第 3 步】每用户资料 + 每日计划
create table if not exists profiles (
  user_id            uuid primary key default auth.uid() references auth.users(id) on delete cascade,
  display_name       text,
  daily_new_words    int not null default 10,
  daily_review_limit int not null default 100,
  created_at         timestamptz not null default now()
);

-- 【第 4 步】文章笔记 / 划线（每用户）
create table if not exists article_notes (
  id             bigint generated by default as identity primary key,
  user_id        uuid not null default auth.uid() references auth.users(id) on delete cascade,
  article_id     int  not null references articles(id) on delete cascade,
  sentence_index int  not null,
  quote          text not null,                 -- 选中的印尼语片段
  note           text not null default '',       -- 笔记内容（可为空＝纯划线）
  color          text not null default 'yellow',
  created_at     timestamptz not null default now()
);
create index if not exists idx_article_notes_user_article on article_notes(user_id, article_id);

-- 【第 5 步】RLS：进度/资料/笔记 只能本人读写；词库/语法/文章/文化 仍公开只读
alter table learning      enable row level security;
alter table checkins      enable row level security;
alter table profiles      enable row level security;
alter table article_notes enable row level security;

drop policy if exists "public all learning" on learning;
drop policy if exists "public all checkins" on checkins;

create policy "own learning"  on learning      for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own checkins"  on checkins      for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own profile"   on profiles      for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "own notes"     on article_notes for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- 【第 6 步】权限：登录用户可读写自己的数据；anon 不再能写进度
grant select, insert, update, delete on learning, checkins, profiles, article_notes to authenticated;
grant usage, select on all sequences in schema public to authenticated;
revoke insert, update, delete on learning, checkins from anon;
-- 说明：words/grammar/articles/culture 维持「anon 公开只读 + 上传脚本 insert」不变，routine 照常工作。
