-- 种草：印尼景点推荐
-- 在 Supabase SQL Editor 中运行此文件

-- 1. 景点表
create table if not exists public.spots (
  id           bigint generated by default as identity primary key,
  name         text not null,
  name_zh      text not null,
  province     text,
  region       text not null,
  category     text not null default 'nature',
  description_zh text,
  description  text,
  cover_url    text,
  maps_url     text,
  submitted_by uuid references auth.users(id),
  submitted_name text,
  view_count   integer not null default 0,
  is_preset    boolean not null default false,
  created_at   timestamptz not null default now()
);
-- 2. 评论表（支持回复 via parent_id）
create table if not exists public.spot_comments (
  id           bigint generated by default as identity primary key,
  spot_id      bigint not null references public.spots(id) on delete cascade,
  user_id      uuid not null references auth.users(id) on delete cascade,
  display_name text,
  content      text not null check (char_length(content) between 1 and 500),
  parent_id    bigint references public.spot_comments(id) on delete cascade,
  created_at   timestamptz not null default now()
);

-- 3. 浏览记录（每用户每景点唯一）
create table if not exists public.spot_views (
  spot_id   bigint not null references public.spots(id) on delete cascade,
  user_id   uuid not null references auth.users(id) on delete cascade,
  viewed_at timestamptz not null default now(),
  primary key (spot_id, user_id)
);

-- RLS
alter table public.spots enable row level security;
alter table public.spot_comments enable row level security;
alter table public.spot_views enable row level security;

-- spots: 全部可读；登录用户可提交自己的
create policy "spots_select"  on public.spots for select using (true);
create policy "spots_insert"  on public.spots for insert with check (auth.uid() = submitted_by);

-- comments: 全部可读；登录用户增删自己的
create policy "spot_comments_select" on public.spot_comments for select using (true);
create policy "spot_comments_insert" on public.spot_comments for insert with check (auth.uid() = user_id);
create policy "spot_comments_delete" on public.spot_comments for delete using (auth.uid() = user_id);

-- views: 用户只看/管自己的
create policy "spot_views_select" on public.spot_views for select using (auth.uid() = user_id);
create policy "spot_views_insert" on public.spot_views for insert with check (auth.uid() = user_id);
create policy "spot_views_update" on public.spot_views for update using (auth.uid() = user_id);

-- grants
grant select              on public.spots          to anon, authenticated;
grant insert              on public.spots          to authenticated;
grant usage, select       on sequence public.spots_id_seq to authenticated;

grant select              on public.spot_comments  to anon, authenticated;
grant insert, delete      on public.spot_comments  to authenticated;
grant usage, select       on sequence public.spot_comments_id_seq to authenticated;

grant select, insert, update on public.spot_views  to authenticated;

-- RPC: 记录浏览（首次则 view_count+1）
create or replace function public.track_spot_view(p_spot_id bigint)
returns void language plpgsql security definer as $$
declare v_new boolean;
begin
  select not exists(
    select 1 from spot_views where spot_id = p_spot_id and user_id = auth.uid()
  ) into v_new;
  insert into spot_views(spot_id, user_id) values (p_spot_id, auth.uid())
  on conflict (spot_id, user_id) do update set viewed_at = now();
  if v_new then
    update spots set view_count = view_count + 1 where id = p_spot_id;
  end if;
end;
$$;
grant execute on function public.track_spot_view(bigint) to authenticated;

-- 预设景点（由管理员以 service role 运行，绕过 RLS）
insert into public.spots (name, name_zh, province, region, category, description_zh, description, maps_url, is_preset) values

('Tanah Lot', '海神庙', '巴厘省', '巴厘', 'culture',
 '建在海中礁石上的印度教神庙，日落时分景色绝美，是巴厘岛最具标志性的打卡地。每逢涨潮，神庙被海水环绕，如梦如幻。',
 'Pura Hindu yang berdiri di atas batu karang di tengah laut, terkenal dengan pemandangan matahari terbenam yang memukau.',
 'https://www.google.com/maps/search/?api=1&query=Tanah+Lot+Bali', true),

('Ubud', '乌布', '巴厘省', '巴厘', 'culture',
 '巴厘岛的艺术与文化中心，有著名的梯田风光、猴子森林和传统市场。这里节奏慢、氛围好，适合深度体验巴厘文化。',
 'Pusat seni dan budaya Bali yang terkenal dengan sawah terasering, Monkey Forest, dan pasar seni tradisional.',
 'https://www.google.com/maps/search/?api=1&query=Ubud+Bali', true),

('Pantai Kuta', '库塔海滩', '巴厘省', '巴厘', 'beach',
 '巴厘岛最著名的海滩，以冲浪、日落和热闹的海边氛围闻名。游客众多，是初到巴厘的必访之地。',
 'Pantai paling terkenal di Bali, populer untuk surfing, menikmati sunset, dan suasana pantai yang ramai.',
 'https://www.google.com/maps/search/?api=1&query=Kuta+Beach+Bali', true),

('Candi Borobudur', '婆罗浮屠', '中爪哇省', '爪哇', 'culture',
 '世界最大的佛教寺庙，建于9世纪，是联合国教科文组织世界遗产。日出时分，云海中的佛塔剪影是一生必看的景色。',
 'Candi Buddha terbesar di dunia, dibangun abad ke-9, Situs Warisan Dunia UNESCO yang luar biasa.',
 'https://www.google.com/maps/search/?api=1&query=Borobudur+Temple+Magelang', true),

('Gunung Bromo', '布罗莫火山', '东爪哇省', '爪哇', 'nature',
 '印尼最著名的活火山，凌晨徒步登观景台看日出，眼前是火山口冒着白烟的壮阔景象，令人震撼。',
 'Gunung berapi aktif yang terkenal di Jawa Timur, pemandangan sunrise di atas lautan pasir vulkanik sangat menakjubkan.',
 'https://www.google.com/maps/search/?api=1&query=Gunung+Bromo+East+Java', true),

('Kota Yogyakarta', '日惹', '日惹特区', '爪哇', 'city',
 '印尼文化之都，有王宫、普兰班南神庙和繁华的马里奥波洛大街。蜡染布、皮影戏和传统美食令人难忘。',
 'Kota budaya Indonesia dengan Keraton, Candi Prambanan, dan Jalan Malioboro yang ramai penuh seni dan kuliner.',
 'https://www.google.com/maps/search/?api=1&query=Yogyakarta+Indonesia', true),

('Danau Toba', '多巴湖', '北苏门答腊省', '苏门答腊', 'nature',
 '世界上最大的火山湖，湖中有一座比新加坡还大的萨摩西岛。巴塔克族文化独特，可体验传统木屋民宿。',
 'Danau vulkanik terbesar di dunia dengan Pulau Samosir di tengahnya, surga budaya Batak yang kaya.',
 'https://www.google.com/maps/search/?api=1&query=Lake+Toba+Sumatra+Indonesia', true),

('Bukit Lawang', '布吉拉旺', '北苏门答腊省', '苏门答腊', 'nature',
 '苏门答腊猩猩保护中心，可以在热带雨林中近距离观察野生猩猩，是生态旅游的绝佳目的地。',
 'Pusat rehabilitasi orangutan Sumatera di tepi Taman Nasional Gunung Leuser, surga ekowisata.',
 'https://www.google.com/maps/search/?api=1&query=Bukit+Lawang+Orangutan+Sumatra', true),

('Taman Nasional Bunaken', '布纳肯国家公园', '北苏拉威西省', '苏拉威西', 'beach',
 '世界顶级潜水圣地之一，拥有超过390种鱼类和垂直珊瑚墙。清澈的海水让潜水爱好者流连忘返。',
 'Taman laut dengan keanekaragaman hayati yang luar biasa, terkenal dengan dinding karang vertikal yang dramatis.',
 'https://www.google.com/maps/search/?api=1&query=Bunaken+National+Marine+Park+Sulawesi', true),

('Tana Toraja', '托拉加', '南苏拉威西省', '苏拉威西', 'culture',
 '独特的葬礼文化让这里闻名世界。人们相信死亡是一段旅程，葬礼可持续数天，场面壮观。悬崖墓穴和传统高脚屋同样令人叹为观止。',
 'Terkenal dengan upacara pemakaman yang megah dan unik, rumah adat Tongkonan, serta makam tebing yang misterius.',
 'https://www.google.com/maps/search/?api=1&query=Tana+Toraja+South+Sulawesi', true),

('Pulau Komodo', '科莫多岛', '东努沙登加拉省', '其他', 'nature',
 '科莫多巨蜥的唯一栖息地，同时拥有迷人的粉红沙滩和丰富的海洋生态系统，浮潜体验一流。',
 'Habitat alami komodo, hewan melata terbesar di dunia, juga memiliki Pantai Pink yang unik dan laut yang kaya.',
 'https://www.google.com/maps/search/?api=1&query=Komodo+Island+Flores+Indonesia', true),

('Raja Ampat', '拉贾安帕特', '西巴布亚省', '其他', 'beach',
 '地球上最丰富的海洋生物多样性所在地，被誉为「世界最后的海洋天堂」。独特的蕈状岛礁和清澈海水令人叹为观止。',
 'Kepulauan dengan biodiversitas laut terkaya di bumi, surganya penyelam dengan koral dan ikan yang tak terhitung.',
 'https://www.google.com/maps/search/?api=1&query=Raja+Ampat+West+Papua+Indonesia', true);
