-- BIPA 模拟测评题库表
-- 在 Supabase SQL Editor 运行：
-- 1) 先执行本文件创建表
-- 2) 再执行 vocab-exam-seed.sql 导入初始题库

create table if not exists public.vocab_exam_bank (
  id bigint generated by default as identity primary key,
  section text not null check (section in ('word', 'sentence', 'reading')),
  difficulty text not null check (difficulty in ('easy', 'medium', 'hard')),
  prompt text not null,
  options jsonb not null check (jsonb_typeof(options) = 'array'),
  answer text not null,
  explain text not null default '',
  passage_title text,
  passage_text text,
  sort_order integer not null default 0,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.vocab_exam_bank enable row level security;

drop policy if exists "vocab_exam_bank_read" on public.vocab_exam_bank;
create policy "vocab_exam_bank_read"
  on public.vocab_exam_bank
  for select
  using (true);

grant select on table public.vocab_exam_bank to anon, authenticated;
